### ISSUE TITLE
Good , this Config also used by FL8000UN perfectly.

### ISSUE THREAD

**Issue by 610312586** [KKKIIINNN/ASUS-FL8000UQ-Hackintosh#1]
这个配置文件也可以完美的应用于FL8000UN这个电脑，我的电脑是这个型号，感谢作者的分享，需要注意的是：
1、如果卡苹果读条，尤其是半透明或者后面出现了那个语音辅助的讲解告诉你按空格进入设置（听不懂的话，你只需要听其中有一个单词是space），需要降级BIOS固件。我从目前最新版的309固件一直降级到305才成功进入苹果系统。
2、作者换了网卡，但是几乎不影响，找一个对应型号的网卡驱动即可，我是直接安装到SLE中，重建驱动缓存就可以驱动WIFI了。
3、今天早晨更新了10.15.4的更新补丁1G多（2020-4-9更新补丁），重点修复了传大文件会系统崩溃那个问题，几乎所有人反馈无痛升级，不过我遇到了声卡驱动异常的情况，重建驱动缓存即可解决。
4、几点特殊说明：
　　触控板驱动几乎算完美驱动，但是不支持轻触。就是说，想用鼠标右键需要双指重按。
　　键盘驱动，目前发现alt和win键是标准匹配的，但是苹果的键盘command是靠近空格的，command相当于win键，所以给我的感觉就是alt和command快捷键反了。。不过这不是作者的错，只是说不习惯，很多人都会考虑直接改掉。。另外因为改了F5到F12的按键，所以mac系统的F5到F12就没有了。。

**Comment by KKKIIINNN** [comment]
触控板的问题可能是因为型号的不同而导致无法使用右键，在UQ上，双指轻触是可以的，也有可能是你的偏好设置里的轻触没有开启。然后F5-F12的问题，如果需要用到这些按键原本的功能的话，可以删除ACPI文件下的SSDT-Fkey.aml,然后使用Karabiner
Elements来进行键位调整，这样就能在使用原本功能的同时也支持Mac的功能

灵玲橙（LLC）Mr.Orange <notifications@github.com> 于 2020年4月9日周四 20:06写道：
