### ISSUE TITLE
在oc引导没有win启动项

### ISSUE THREAD

**Issue by liangzad** [KKKIIINNN/ASUS-FL8000UQ-Hackintosh#2]
我也不知道是什么情况，不管是oc还是ndk都没有win的启动项，只有clover才有.....

**Comment by HF0920** [comment]
我刚好相反 clover没有Mac启动项 oc有
还有就是我这bcm94352z的网卡搭配此efi可以免驱运行 就是WiFi信号很不稳定 不知道开发者能否单独对bcm94352z进行一下适配

**Comment by HF0920** [comment]
> 我刚好相反 clover没有Mac启动项 oc有
> 还有就是我这bcm94352z的网卡搭配此efi可以免驱运行 就是WiFi信号很不稳定 不知道开发者能否单独对bcm94352z进行一下适配

另外提一句 我的机型是FL8000UF不知道这个有没有影响
貌似开发者的efi 顽石五代那几个机型都可以通用

**Comment by liangzad** [comment]
> 我刚好相反 clover没有Mac启动项 oc有
> 还有就是我这bcm94352z的网卡搭配此efi可以免驱运行 就是WiFi信号很不稳定 不知道开发者能否单独对bcm94352z进行一下适配

相信作者会越来越好的👌

**Comment by KKKIIINNN** [comment]
@HF0920 @liangzad 请问你们是双硬盘双系统还是单硬盘双系统

**Comment by liangzad** [comment]
> @HF0920 @liangzad 请问你们是双硬盘双系统还是单硬盘双系统

我的是龙凤胎（单硬盘双系统）😂

**Comment by KKKIIINNN** [comment]
> 我刚好相反 clover没有Mac启动项 oc有
> 还有就是我这bcm94352z的网卡搭配此efi可以免驱运行 就是WiFi信号很不稳定 不知道开发者能否单独对bcm94352z进行一下适配

对于DW1560这张网卡，你可以去黑果小兵或者远景论坛查找驱动方式，如果需要我的帮助，可以加QQ：211560569

**Comment by KKKIIINNN** [comment]
> > @HF0920 @liangzad 请问你们是双硬盘双系统还是单硬盘双系统
> 
> 我的是龙凤胎（单硬盘双系统）😂

这就非常的麻烦，因为我的EFI是基于双硬盘双系统来建立的，最近我也在研究单硬盘引导，等我有了结果会告诉你们。

**Comment by HF0920** [comment]
> @HF0920 @liangzad 请问你们是双硬盘双系统还是单硬盘双系统

我是双硬盘双系统 Mac在固态 win10在机械盘 主要win10做调试

**Comment by HF0920** [comment]
> > 我刚好相反 clover没有Mac启动项 oc有
> > 还有就是我这bcm94352z的网卡搭配此efi可以免驱运行 就是WiFi信号很不稳定 不知道开发者能否单独对bcm94352z进行一下适配
> 
> 对于DW1560这张网卡，你可以去黑果小兵或者远景论坛查找驱动方式，如果需要我的帮助，可以加QQ：211560569

按照他们的方法 我这电脑直接WiFi和声音都没了 也问过几个人 说可能是驱动冲突什么的 QQ已加 貌似你有添加验证 还是请加下我吧 QQ:1937656307 期待作者的帮助

**Comment by KKKIIINNN** [comment]
> > @HF0920 @liangzad 请问你们是双硬盘双系统还是单硬盘双系统
> 
> 我的是龙凤胎（单硬盘双系统）😂

对于单硬盘双系统，暂时没有什么好的解决办法，折中的方法是在另外一块硬盘上开辟一个ESP分区用来存放Mac引导，以此来达成双引导双系统的效果

**Comment by liangzad** [comment]
> > > @HF0920 @liangzad 请问你们是双硬盘双系统还是单硬盘双系统
> > 
> > 
> > 我的是龙凤胎（单硬盘双系统）😂
> 
> 对于单硬盘双系统，暂时没有什么好的解决办法，折中的方法是在另外一块硬盘上开辟一个ESP分区用来存放Mac引导，以此来达成双引导双系统的效果

谢谢大佬的讲解，我试试，大佬幸苦了！😳
