### ISSUE TITLE
无线网卡

### ISSUE THREAD

**Issue by svenxuxm** [KKKIIINNN/ASUS-FL8000UQ-Hackintosh#3]
这个版本的Wi-Fi和蓝牙会不会有什么小毛病，能正常使用隔空投送、接力、随航吗？谢谢楼主了

**Comment by KKKIIINNN** [comment]
暂时没有发现问题，我没有ios设备，所以无法测试这些功能，按照黑果小兵博客的说法，随航可能有点问题，其他功能都正常。
