### ISSUE TITLE
 显示器问题

### ISSUE THREAD

**Issue by Air75** [KKKIIINNN/ASUS-FL8000UQ-Hackintosh#4]
大佬，不知道你的有没有问题。我现在用的是你最新的efi，系统是10.15.5 外接显示器息屏后就无法自动唤醒，只有再开关一下显示器的开关才能重新显示。

**Comment by KKKIIINNN** [comment]
10.15.5砍掉了对HDMI的支持，所以外接显示器会出现一些小问题，这个暂时没有好的解决办法
