### ISSUE TITLE
Big Sur中DW1820A无法加载

### ISSUE THREAD

**Issue by liangzad** [KKKIIINNN/ASUS-FL8000UQ-Hackintosh#6]
今天刚装的b9的系统，有驱动（黑果小兵的），蓝牙能用，Wi-Fi无法加载，pci没有显示1820A，只有退到15.7才能使用。

**Comment by KKKIIINNN** [comment]
尝试屏蔽针脚

**Comment by KKKIIINNN** [comment]
或者有屏蔽的话去掉屏蔽

**Comment by gaoweijun2018** [comment]
同样的问题,需要屏蔽哪个针脚?

**Comment by KKKIIINNN** [comment]
黑果小兵的博客上有详细的说明

gaoweijun2018 <notifications@github.com> 于 2020年12月10日周四 16:24写道：

**Comment by KKKIIINNN** [comment]
> 同样的问题,需要屏蔽哪个针脚?

黑果小兵的博客上有详细的说明
