### ISSUE TITLE
Big Sur beta10的问题

### ISSUE THREAD

**Issue by liangzad** [KKKIIINNN/ASUS-FL8000UQ-Hackintosh#7]
安装beta9都可以常规操作，就是beta10就不行了，不知道是什么原因，进安装界面就是白屏，用了小兵的方法重制nvarm还是不行，手动升级oc到0.6.2也不行，所有的驱动都是最新的，难搞哦！大神有木有什么高招啊？

**Comment by KKKIIINNN** [comment]
尝试使用OpenCore0.6.3

**Comment by liangzad** [comment]
> 尝试使用OpenCore0.6.3

好的👌谢谢🙏大神幸苦了☕️
